### PR TITLE
Add serviceWorkerFileName option

### PR DESCRIPTION
**Pull request by jniechcial**
### Motivation
I am using ember-service-worker with OneSignal Push Notifications. Their SDK provides you service worker with following code:
```
self.importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```
And they claim that it's filename (`OneSignalSDKWorker.js`) is required for their SDK to work.

### Solution
I solved it by using the output service worker from `ember-service-worker` as an `importScript` in the OneSignalSDK worker:
```
self.importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
self.importScripts('sw.js');
```
However, `sw-registration.js` is always pointing to `sw.js`. This PR adds possibility to define which service worker should be registered while still producing the output to `sw.js`.

I still wonder if it's best possible solution or maybe there is some other way that I didn't think about. What do you think?

PS. I feel that my naming (`serviceWorkerFileName`) is rather confusing and should be changed before merge. Looking forward to your proposition if you agree we should move forward with it.

### CODE REVIEW

**Comment by eshtadc** [comment]
I know this is pretty old so I understand if you're no longer interested, but I'd be interested in pursuing this. We'd need to first get this up to the current code. Then we also need to look at the entry point generation as that also uses the 'sw.js' filename. In fact, I think you don't have to pass it in to the `ServiceWorkerBuilder` class as that class defines it internally in the entry point filename constants. I would also want to default the option in `included` like we do for other option values. Any more thoughts as to the option name from `serverWorkerFilename`.

**Comment by jniechcial** [comment]
This was quite a while ago, true! I will try to get it to shape but will need to timebox it. Will write back over the weekend ;)

**Comment by jniechcial** [comment]
Sorry, can't make it! :(

**Comment by eshtadc** [comment]
No worries @jniechcial - thanks for the original contribution. I'll try to get a new PR from your work here.

**Comment by eshtadc** [comment]
Created issue: https://github.com/DockYard/ember-service-worker/issues/149

**Comment by eshtadc** [comment]
Closing in favor of https://github.com/DockYard/ember-service-worker/pull/150

**Pull request closed without merging**
