### PR TITLE
Upgrade babel

### PR DESCRIPTION
**Pull request by eshtadc**
Replaces PR #96 with permission from @cibernox in order to have a branch that I can work on too.

### CODE REVIEW

**Comment by cibernox** [comment]
@eshtadc should I close #96 now?

**Comment by eshtadc** [comment]
@cibernox Thanks for checking. I went ahead and closed it when I linked to it. You're all set.

**Comment by eshtadc** [comment]
Appears that the tests weren't working due to an older version of babel being included by older ember-cli and a misconfiguration of the preset plugins.

**Comment by cibernox** [comment]
This is great!

**Pull request merged**
