### PR TITLE
Adds the immediate claim technique which a SPA should do

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by NekR** [comment]
It's `e.waitUntil(promise)`, not `return promise`.

**Comment by martndemus** [comment]
Can you explain a little bit more?

**Comment by NekR** [comment]
https://www.w3.org/TR/service-workers/#extendable-event

**Comment by martndemus** [comment]
@NekR That's not really explaining. Could you explain to me why I should use `waitUntil`?

**Comment by NekR** [comment]
You don't have to, but also you don't have to return anything from listener. It makes no sense to return promise from listener and is rather confused. It doesn't show your intent in the code and can confuse everyone as it confuses me right now, because in context of SW it looks like you wanted to "block" event completion while promise is working.

Anyway, regardless your intent, calling `return` makes zero sense here and has wrong impression.

**Pull request merged**
