### PR TITLE
Fix for ROOT_URL not being replaced with Ember 3.5

### PR DESCRIPTION
**Pull request by erkie**
Fixes: https://github.com/DockYard/ember-service-worker/issues/125

The fix can be found in the final commit. Added a test to ensure it works. Had to upgrade the `simple-app` fixture project, and ran `ember-cli-update` on the main project as well. That might be a bit controversial, I do not know the effect it has on the compatibility of the addon...

I'd be happy to amend the PR and only include the fix-commit.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
in my app, I was able to get away with _just_ this change and have my ROOT_URL problem https://github.com/DockYard/ember-service-worker/pull/132
we should probably upgrade everything after this change.

(I also confirmed this by ensuring that {{ROOT_URL}} is present in my registration script with the latest release by deleting my node_modules folder and re-building)

**Comment by eshtadc** [comment]
I'm currently on an upgrade spree to get dependencies up to date. @NullVoxPopuli @erkie  Am I understanding correctly that you are confirming that https://github.com/DockYard/ember-service-worker/pull/132 works for your project? Also sounds like a new issue is warranted for the cache-buster removal as well, yes?

**Comment by erkie** [comment]
@eshtadc that is correct. However I am not 100% sure about the cache-buster. I haven’t really confirmed but during debugging this issue it did definitely disappear.

**Comment by NullVoxPopuli** [comment]
@eshtadc yeah, #132 solves the issue with https://emberclear.io

**Comment by eshtadc** [comment]
After investigation, closing in favor of #132. Continuing to look into missing `const` with updated rollup prior to creating a new release.

**Pull request closed without merging**
