### PR TITLE
External dependencies

### PR DESCRIPTION
**Pull request by CodingDive**
This PR hopes to add support for importing external dependencies within the service-worker by bundling dependencies into the sw.js bundle.

At the very beginning (August in the commit history) I implemented the same changes as @dadleyy. https://github.com/DockYard/ember-service-worker/issues/63
Inside the `package.json` of my Ember app, I was consuming the fork directly from GitHub which worked fine. After recently upgrading our `Ember` project to version 3.5.1, the fix stopped working and I got a lot of `Rollup` and dependency related issues. The package was tested with 3.5.1 but I do need some guidance on how to test different ember versions and write automated tests for my changes. 

I also thought I could maybe fix another [issue](https://github.com/DockYard/ember-service-worker/issues/133) by allowing one to configure babel. As the issues were not related to each other, the changes didn't make it into the final version and I'm saving this issue for another day or someone else.

I wasn't able to run the tests yet due to build errors. `The loader.js addon is missing from your project, please add it to your package.json` and after adding it, another build error `Missing template processor`. If anyone can shed some light on what the best way is to get the tests up and running, please let me know.

This is my first non trivial PR so any feedback is greatly appreciated.

### CODE REVIEW

**Comment by eshtadc** [comment]
@CodingDive I wonder if this is still relevant given the dependency updates that have been made lately?

**Comment by CodingDive** [comment]
I'm no longer working with Ember or this project. @MarcoUmpierrez can you confirm that the PR can be closed and is no longer relevant?

**Comment by MarcoUmpierrez** [comment]
Sorry for the delay. Yes, you can close this PR. Thanks.

**Comment by eshtadc** [comment]
Thanks for confirming @MarcoUmpierrez

**Pull request closed without merging**
