### PR TITLE
Rollup sw.js to allow imports and avoid extra importScript.

### PR DESCRIPTION
**Pull request by rwjblue**
* Changes primary API to use `service-worker/index.js` as the entry
  point (instead of `service-worker/<addon-name>.js`). This allows much
  less collisions in the files used for local utilities, and provides a
  nicer API for consumers.
* Allows internal imports from within a given plugins `service-worker`
  directory (via `import foo from './foo'`).
* Ensure `VERSION` constant updates for each rebuild (previously would
  use the same value for rebuilds).

### CODE REVIEW

**Comment by rwjblue** [comment]
Output in `dist/sw.js` from `ember build` within the addon:

```js
(function () {
  var FETCH_HANDLERS = [];

  self.addEventListener('fetch', function fetchEventListenerCallback(event) {
    var resolver = function fetchResolver(resolve, reject, index) {
      if (!index) {
        index = 0;
      }

      if (index >= FETCH_HANDLERS.length) {
        resolve(fetch(event.request));
      }

      var handler = FETCH_HANDLERS[index];

      handler(event).then(function (response) {
        if (response) {
          return resolve(response);
        } else {
          return resolver(resolve, reject, index + 1);
        }
      })['catch'](reject);
    };

    event.respondWith(new Promise(resolver));
  });

  self.addEventListener('install', function installEventListenerCallback(event) {
    return self.skipWaiting();
  });

  self.addEventListener('activate', function installEventListenerCallback(event) {
    return self.clients.claim();
  });

  self.addFetchListener = function addFetchListener(handler) {
    FETCH_HANDLERS.push(handler);
  };
})();
```

**Comment by rwjblue** [comment]
Looks like it is stripping `VERSION` because it isn't used (so it is removed during dead code elimination).

**Comment by martndemus** [comment]
Should we namespace the files from each plugin?

**Comment by rwjblue** [comment]
Still a small amount of tweaks to make here. Trying to test various combos in a new app just to make sure things work well. Marked this as WIP in the meantime.

**Comment by rwjblue** [comment]
OK, just pushed an update.  There are a few major/breaking changes, but I think this is in line with what we discussed at EmberCamp.

The largest (breaking) change is that you now use `service-worker/index.js` instead of `service-work/<addon-name>.js`.  I'm happy to update the existing plugins to this format once this has landed.

**Comment by rwjblue** [comment]
I submitted https://github.com/DockYard/ember-service-worker-asset-cache/pull/5 as an example of the upgrade changes required.

**Comment by rwjblue** [comment]
Here is the output of an app that is consuming this branch and the branch from https://github.com/DockYard/ember-service-worker-asset-cache/pull/5:

```js
var VERSION = '1468559715234';

var FETCH_HANDLERS = [];

self.addEventListener('fetch', function fetchEventListenerCallback(event) {
  var resolver = function fetchResolver(resolve, reject, index) {
    if (!index) {
      index = 0;
    }

    if (index >= FETCH_HANDLERS.length) {
      resolve(fetch(event.request));
    }

    var handler = FETCH_HANDLERS[index];

    handler(event).then(function (response) {
      if (response) {
        return resolve(response);
      } else {
        return resolver(resolve, reject, index + 1);
      }
    })['catch'](reject);
  };

  event.respondWith(new Promise(resolver));
});

self.addEventListener('install', function installEventListenerCallback(event) {
  return self.skipWaiting();
});

self.addEventListener('activate', function installEventListenerCallback(event) {
  return self.clients.claim();
});

function addFetchListener(handler) {
  FETCH_HANDLERS.push(handler);
}

var CACHE_NAME = 'asset-cache-' + VERSION;

self.addEventListener('install', function (event) {
  event.waitUntil(caches.open(CACHE_NAME).then(function (cache) {
    cache.add(self.registration.scope);
    return fetch('files.json').then(function (response) {
      return response.json();
    }).then(function (json) {
      var files = json.files.map(function (file) {
        return json.prepend ? json.prepend + file : file;
      }).map(function (path) {
        ;
        return new Request(path, { mode: 'no-cors' });
      });

      return cache.addAll(files);
    })['catch'](function () {});
  }));
});

addFetchListener(function (event) {
  return caches.match(event.request, { cacheName: CACHE_NAME }).then(function (response) {
    if (response) {
      return response;
    } else if (event.request.headers.get('accept').indexOf('text/html') >= 0) {
      return caches.match(self.registration.scope);
    }
  });
});

self.addEventListener('activate', function (event) {
  event.waitUntil(caches.keys().then(function (cacheNames) {
    cacheNames.forEach(function (cacheName) {
      if (cacheName.indexOf('asset-cache-') === 0 && cacheName !== CACHE_NAME) {
        caches['delete'](cacheName);
      }
    });
  }));
});
```

As you can see, the `import`'s are resolved and the contents inlined directly (so no need for a loader) and that the namespacing via (from https://github.com/DockYard/ember-service-worker-asset-cache/pull/5) the `import { addFetchListener } from 'ember-service-worker';` is working properly.

**Comment by rwjblue** [comment]
I believe I can also allow imports from addons in general if we want. Perhaps I should change the addon specific service worker files to be namespaced at `<addon-name>/service-worker/index` instead. That leaves us open to allowing imports from an addons `addon/` directory without having to do any special rewriting/merging.

**Comment by martndemus** [comment]
> Perhaps I should change the addon specific service worker files to be namespaced at <addon-name>/service-worker/index instead.

That makes sense.

Everything else LGTM.

**Comment by rwjblue** [comment]
OK, updated to use:

```js
import something from 'ADDON_NAME/service-worker';
```

I also updated https://github.com/DockYard/ember-service-worker-asset-cache/pull/5 to match these changes. I am happy to submit PR's to the various other plugin repos once this lands.

---

If you don't mind, I'd like to land this (its already a largish changeset), then follow up in a separate PR to provide config and allow `addon/` directory imports.

**Comment by martndemus** [comment]
:+1:

**Comment by rwjblue** [comment]
OK, all of the existing plugins have PR's ready to go once this lands in a released version:

* https://github.com/DockYard/ember-service-worker-cache-first/pull/1
* https://github.com/DockYard/ember-service-worker-cache-fallback/pull/4
* https://github.com/DockYard/ember-service-worker-asset-cache/pull/5

**Pull request merged**
