### PR TITLE
Update ember-fastboot-addon-tests

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by simonihmig** [comment]
@martndemus the failing tests should be easily fixed by updating `ember-fastboot-addon-tests`! The old version used here still calls `ember fastboot` (see Travis log https://travis-ci.org/DockYard/ember-service-worker/jobs/256935032) to spin up the FastBoot server which is not supported anymore!

**Comment by martndemus** [comment]
@simonihmig After updating the addon, the test still fail, but the error is not helpful, can you take a look?

**Comment by simonihmig** [comment]
Hm, not sure. Passes for node 6, fails in node 8 with same error I have no idea about, and in node 4 because of `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`(https://travis-ci.org/DockYard/ember-service-worker/jobs/275973344#L2405-L2406), also not sure where this comes from. Will have to investigate this...

If you need to fix the tests now, maybe you can disable the fastboottest scenario, so we can easily reenable that when fixed...

**Comment by simonihmig** [comment]
This explains the failure in node 4: https://github.com/emberjs/data/issues/5177

**Comment by eshtadc** [comment]
Fingers crossed - they work locally now after the other upgrades when I run it with version 0.4.0.

**Comment by eshtadc** [comment]
This PR also removes support for node 4 (which is no longer supported)
https://github.com/nodejs/Release

**Pull request merged**
